### ISSUE TITLE
Can't run the code correctly

### ISSUE THREAD

**Issue by wwwangzhch** [sino30535/DDPG-stock-market-test#1]
Hi, thanks for your contribution, but when I download your code and run it on my computer, I found the result seems incorrect. In every episode, the codes always print "Episode: xxx, Reward: 1.00, Qmax: 0.0000" and action tesnor in every epoch are all [0.03, 0.03 ... 0.03]. Bellow are my parameters setting, please let me know if I  am wrong.
`python stock_trading.py -p cnn -b True -ts 20180102 -te 20180730 -w 10`**

**Comment by wkzqn** [comment]
Hello, I have encountered the same problem. Have you solved this problem?

**Comment by sino30535** [comment]
Hi, I think this is printing issue. In model/ddpg/ddpg.py, line 185, change printing format to
print('Episode: {:d}, Reward: {:.5f}, Qmax: {:.5f}'.format(i, np.exp(ep_reward), (ep_ave_max_q / float(j))))
You will see correct reward for each episode. For action tensor, you will probably see action start to change after ~1000 episode training.

**Comment by wkzqn** [comment]
Thank you very much. I'll try it later.
